//go:build windows || unix

package midi

import (
	sdl "github.com/Zyko0/go-sdl3/sdl"
	puregogen "github.com/Zyko0/purego-gen"
	purego "github.com/ebitengine/purego"
	"runtime"
	"unsafe"
)

// File generated by github.com/Zyko0/purego-gen. DO NOT EDIT.

var (
	// Library handles
	_hnd_midi uintptr
	// Symbols
	// midi
	_addr_NativeMidi_Init        uintptr
	_addr_NativeMidi_Quit        uintptr
	_addr_NativeMidi_LoadSong_IO uintptr
	_addr_NativeMidi_LoadSong    uintptr
	_addr_NativeMidi_DestroySong uintptr
	_addr_NativeMidi_Start       uintptr
	_addr_NativeMidi_Pause       uintptr
	_addr_NativeMidi_Resume      uintptr
	_addr_NativeMidi_Stop        uintptr
	_addr_NativeMidi_Active      uintptr
)

func initialize() {
	var err error

	// Symbols midi
	_addr_NativeMidi_Init, err = puregogen.OpenSymbol(_hnd_midi, "NativeMidi_Init")
	if err != nil {
		panic("cannot puregogen.OpenSymbol: NativeMidi_Init")
	}
	_addr_NativeMidi_Quit, err = puregogen.OpenSymbol(_hnd_midi, "NativeMidi_Quit")
	if err != nil {
		panic("cannot puregogen.OpenSymbol: NativeMidi_Quit")
	}
	_addr_NativeMidi_LoadSong_IO, err = puregogen.OpenSymbol(_hnd_midi, "NativeMidi_LoadSong_IO")
	if err != nil {
		panic("cannot puregogen.OpenSymbol: NativeMidi_LoadSong_IO")
	}
	_addr_NativeMidi_LoadSong, err = puregogen.OpenSymbol(_hnd_midi, "NativeMidi_LoadSong")
	if err != nil {
		panic("cannot puregogen.OpenSymbol: NativeMidi_LoadSong")
	}
	_addr_NativeMidi_DestroySong, err = puregogen.OpenSymbol(_hnd_midi, "NativeMidi_DestroySong")
	if err != nil {
		panic("cannot puregogen.OpenSymbol: NativeMidi_DestroySong")
	}
	_addr_NativeMidi_Start, err = puregogen.OpenSymbol(_hnd_midi, "NativeMidi_Start")
	if err != nil {
		panic("cannot puregogen.OpenSymbol: NativeMidi_Start")
	}
	_addr_NativeMidi_Pause, err = puregogen.OpenSymbol(_hnd_midi, "NativeMidi_Pause")
	if err != nil {
		panic("cannot puregogen.OpenSymbol: NativeMidi_Pause")
	}
	_addr_NativeMidi_Resume, err = puregogen.OpenSymbol(_hnd_midi, "NativeMidi_Resume")
	if err != nil {
		panic("cannot puregogen.OpenSymbol: NativeMidi_Resume")
	}
	_addr_NativeMidi_Stop, err = puregogen.OpenSymbol(_hnd_midi, "NativeMidi_Stop")
	if err != nil {
		panic("cannot puregogen.OpenSymbol: NativeMidi_Stop")
	}
	_addr_NativeMidi_Active, err = puregogen.OpenSymbol(_hnd_midi, "NativeMidi_Active")
	if err != nil {
		panic("cannot puregogen.OpenSymbol: NativeMidi_Active")
	}

	iInit = func() bool {
		_r0, _, _ := purego.SyscallN(_addr_NativeMidi_Init)
		__r0 := uint8(_r0) != 0
		return __r0
	}
	iQuit = func() {
		purego.SyscallN(_addr_NativeMidi_Quit)
	}
	iLoadSong_IO = func(src *sdl.IOStream, closeio bool) *Song {
		_r0, _, _ := purego.SyscallN(_addr_NativeMidi_LoadSong_IO, uintptr(unsafe.Pointer(src)), puregogen.BoolToUintptr(closeio))
		__r0 := (*Song)(*(*unsafe.Pointer)(unsafe.Pointer(&_r0)))
		runtime.KeepAlive(src)
		return __r0
	}
	iLoadSong = func(path string) *Song {
		_r0, _, _ := purego.SyscallN(_addr_NativeMidi_LoadSong, uintptr(unsafe.Pointer(puregogen.BytePtrFromString(path))))
		__r0 := (*Song)(*(*unsafe.Pointer)(unsafe.Pointer(&_r0)))
		runtime.KeepAlive(path)
		return __r0
	}
	iDestroySong = func(song *Song) {
		purego.SyscallN(_addr_NativeMidi_DestroySong, uintptr(unsafe.Pointer(song)))
		runtime.KeepAlive(song)
	}
	iStart = func(song *Song, loops int32) {
		purego.SyscallN(_addr_NativeMidi_Start, uintptr(unsafe.Pointer(song)), uintptr(loops))
		runtime.KeepAlive(song)
	}
	iPause = func() {
		purego.SyscallN(_addr_NativeMidi_Pause)
	}
	iResume = func() {
		purego.SyscallN(_addr_NativeMidi_Resume)
	}
	iStop = func() {
		purego.SyscallN(_addr_NativeMidi_Stop)
	}
	iActive = func() bool {
		_r0, _, _ := purego.SyscallN(_addr_NativeMidi_Active)
		__r0 := uint8(_r0) != 0
		return __r0
	}
	purego.RegisterLibFunc(&iSetVolume, _hnd_midi, "NativeMidi_SetVolume")
}
