package midi

import sdl "github.com/Zyko0/go-sdl3/sdl"

// Code generated by cmd/ffi2go. DO NOT EDIT.

var (
	// NativeMidi_Init => Initialize the native MIDI subsystem.
	//
	//puregogen:library path:windows=midi.dll path:unix=midi.so alias=midi
	//puregogen:function symbol=NativeMidi_Init
	iInit func() bool

	// NativeMidi_Quit => Shut down the native MIDI subsystem.
	//
	//puregogen:function symbol=NativeMidi_Quit
	iQuit func()

	// NativeMidi_LoadSong_IO => Load a MIDI song from an SDL_IOStream.
	//
	//puregogen:function symbol=NativeMidi_LoadSong_IO
	iLoadSong_IO func(src *sdl.IOStream, closeio bool) *Song

	// NativeMidi_LoadSong => Load a MIDI song from a file path.
	//
	//puregogen:function symbol=NativeMidi_LoadSong
	iLoadSong func(path string) *Song

	// NativeMidi_DestroySong => Free a song and the resources it holds.
	//
	//puregogen:function symbol=NativeMidi_DestroySong
	iDestroySong func(song *Song)

	// NativeMidi_Start => Start playing a song, replacing the one currently playing.
	//
	//puregogen:function symbol=NativeMidi_Start
	iStart func(song *Song, loops int32)

	// NativeMidi_Pause => Pause playback of the current song.
	//
	//puregogen:function symbol=NativeMidi_Pause
	iPause func()

	// NativeMidi_Resume => Resume playback of a paused song.
	//
	//puregogen:function symbol=NativeMidi_Resume
	iResume func()

	// NativeMidi_Stop => Stop playback of the current song.
	//
	//puregogen:function symbol=NativeMidi_Stop
	iStop func()

	// NativeMidi_Active => Query whether a song is currently playing.
	//
	//puregogen:function symbol=NativeMidi_Active
	iActive func() bool

	// NativeMidi_SetVolume => Set the volume applied to MIDI playback.
	//
	//puregogen:function symbol=NativeMidi_SetVolume
	iSetVolume func(volume float32)
)
