//go:build js

package midi

import (
	"github.com/Zyko0/go-sdl3/sdl"
)

// Written by hand rather than generated by cmd/jsgen: SDL_native_midi has no
// emscripten backend, so there are no symbols in the wasm module to bind to
// and generated shims would fail on lookup. These stubs behave like the
// upstream dummy backend instead — Init reports failure and nothing plays.
func initialize() {
	iInit = func() bool { return false }
	iQuit = func() {}
	iLoadSong_IO = func(src *sdl.IOStream, closeio bool) *Song { return nil }
	iLoadSong = func(path string) *Song { return nil }
	iDestroySong = func(song *Song) {}
	iStart = func(song *Song, loops int32) {}
	iPause = func() {}
	iResume = func() {}
	iStop = func() {}
	iActive = func() bool { return false }
	iSetVolume = func(volume float32) {}
}
