package sdl

// Code generated by cmd/ffi2go. DO NOT EDIT.

// SDL_AsyncIOTaskType - Types of asynchronous I/O tasks.
// (https://wiki.libsdl.org/SDL3/SDL_AsyncIOTaskType)
type AsyncIOTaskType uint32

const (
	ASYNCIO_TASK_READ  AsyncIOTaskType = 0
	ASYNCIO_TASK_WRITE AsyncIOTaskType = 1
	ASYNCIO_TASK_CLOSE AsyncIOTaskType = 2
)

// SDL_AsyncIOResult - Possible outcomes of an asynchronous I/O task.
// (https://wiki.libsdl.org/SDL3/SDL_AsyncIOResult)
type AsyncIOResult uint32

const (
	ASYNCIO_COMPLETE AsyncIOResult = 0
	ASYNCIO_FAILURE  AsyncIOResult = 1
	ASYNCIO_CANCELED AsyncIOResult = 2
)

// SDL_PropertyType - SDL property type
// (https://wiki.libsdl.org/SDL3/SDL_PropertyType)
type PropertyType uint32

const (
	PROPERTY_TYPE_INVALID PropertyType = 0
	PROPERTY_TYPE_POINTER PropertyType = 1
	PROPERTY_TYPE_STRING  PropertyType = 2
	PROPERTY_TYPE_NUMBER  PropertyType = 3
	PROPERTY_TYPE_FLOAT   PropertyType = 4
	PROPERTY_TYPE_BOOLEAN PropertyType = 5
)

// SDL_ThreadPriority - The SDL thread priority.
// (https://wiki.libsdl.org/SDL3/SDL_ThreadPriority)
type ThreadPriority uint32

const (
	THREAD_PRIORITY_LOW           ThreadPriority = 0
	THREAD_PRIORITY_NORMAL        ThreadPriority = 1
	THREAD_PRIORITY_HIGH          ThreadPriority = 2
	THREAD_PRIORITY_TIME_CRITICAL ThreadPriority = 3
)

// SDL_ThreadState - The SDL thread state.
// (https://wiki.libsdl.org/SDL3/SDL_ThreadState)
type ThreadState uint32

const (
	THREAD_UNKNOWN  ThreadState = 0
	THREAD_ALIVE    ThreadState = 1
	THREAD_DETACHED ThreadState = 2
	THREAD_COMPLETE ThreadState = 3
)

// SDL_IOStatus - [SDL_IOStream](SDL_IOStream) status, set by a read or write operation.
// (https://wiki.libsdl.org/SDL3/SDL_IOStatus)
type IOStatus uint32

const (
	IO_STATUS_READY     IOStatus = 0
	IO_STATUS_ERROR     IOStatus = 1
	IO_STATUS_EOF       IOStatus = 2
	IO_STATUS_NOT_READY IOStatus = 3
	IO_STATUS_READONLY  IOStatus = 4
	IO_STATUS_WRITEONLY IOStatus = 5
)

// SDL_IOWhence - Possible `whence` values for [SDL_IOStream](SDL_IOStream) seeking.
// (https://wiki.libsdl.org/SDL3/SDL_IOWhence)
type IOWhence uint32

const (
	IO_SEEK_SET IOWhence = 0
	IO_SEEK_CUR IOWhence = 1
	IO_SEEK_END IOWhence = 2
)

// SDL_AudioFormat - Audio format.
// (https://wiki.libsdl.org/SDL3/SDL_AudioFormat)
type AudioFormat uint32

const (
	AUDIO_UNKNOWN AudioFormat = 0
	AUDIO_U8      AudioFormat = 8
	AUDIO_S8      AudioFormat = 32776
	AUDIO_S16LE   AudioFormat = 32784
	AUDIO_S16BE   AudioFormat = 36880
	AUDIO_S32LE   AudioFormat = 32800
	AUDIO_S32BE   AudioFormat = 36896
	AUDIO_F32LE   AudioFormat = 33056
	AUDIO_F32BE   AudioFormat = 37152
	AUDIO_S16     AudioFormat = 32784
	AUDIO_S32     AudioFormat = 32800
	AUDIO_F32     AudioFormat = 33056
)

// SDL_BlendOperation - The blend operation used when combining source and destination pixel components.
// (https://wiki.libsdl.org/SDL3/SDL_BlendOperation)
type BlendOperation uint32

const (
	BLENDOPERATION_ADD          BlendOperation = 1
	BLENDOPERATION_SUBTRACT     BlendOperation = 2
	BLENDOPERATION_REV_SUBTRACT BlendOperation = 3
	BLENDOPERATION_MINIMUM      BlendOperation = 4
	BLENDOPERATION_MAXIMUM      BlendOperation = 5
)

// SDL_BlendFactor - The normalized factor used to multiply pixel components.
// (https://wiki.libsdl.org/SDL3/SDL_BlendFactor)
type BlendFactor uint32

const (
	BLENDFACTOR_ZERO                BlendFactor = 1
	BLENDFACTOR_ONE                 BlendFactor = 2
	BLENDFACTOR_SRC_COLOR           BlendFactor = 3
	BLENDFACTOR_ONE_MINUS_SRC_COLOR BlendFactor = 4
	BLENDFACTOR_SRC_ALPHA           BlendFactor = 5
	BLENDFACTOR_ONE_MINUS_SRC_ALPHA BlendFactor = 6
	BLENDFACTOR_DST_COLOR           BlendFactor = 7
	BLENDFACTOR_ONE_MINUS_DST_COLOR BlendFactor = 8
	BLENDFACTOR_DST_ALPHA           BlendFactor = 9
	BLENDFACTOR_ONE_MINUS_DST_ALPHA BlendFactor = 10
)

// SDL_PixelFormat - Pixel format.
// (https://wiki.libsdl.org/SDL3/SDL_PixelFormat)
type PixelFormat uint32

const (
	PIXELFORMAT_UNKNOWN       PixelFormat = 0
	PIXELFORMAT_INDEX1LSB     PixelFormat = 286261504
	PIXELFORMAT_INDEX1MSB     PixelFormat = 287310080
	PIXELFORMAT_INDEX2LSB     PixelFormat = 470811136
	PIXELFORMAT_INDEX2MSB     PixelFormat = 471859712
	PIXELFORMAT_INDEX4LSB     PixelFormat = 303039488
	PIXELFORMAT_INDEX4MSB     PixelFormat = 304088064
	PIXELFORMAT_INDEX8        PixelFormat = 318769153
	PIXELFORMAT_RGB332        PixelFormat = 336660481
	PIXELFORMAT_XRGB4444      PixelFormat = 353504258
	PIXELFORMAT_XBGR4444      PixelFormat = 357698562
	PIXELFORMAT_XRGB1555      PixelFormat = 353570562
	PIXELFORMAT_XBGR1555      PixelFormat = 357764866
	PIXELFORMAT_ARGB4444      PixelFormat = 355602434
	PIXELFORMAT_RGBA4444      PixelFormat = 356651010
	PIXELFORMAT_ABGR4444      PixelFormat = 359796738
	PIXELFORMAT_BGRA4444      PixelFormat = 360845314
	PIXELFORMAT_ARGB1555      PixelFormat = 355667970
	PIXELFORMAT_RGBA5551      PixelFormat = 356782082
	PIXELFORMAT_ABGR1555      PixelFormat = 359862274
	PIXELFORMAT_BGRA5551      PixelFormat = 360976386
	PIXELFORMAT_RGB565        PixelFormat = 353701890
	PIXELFORMAT_BGR565        PixelFormat = 357896194
	PIXELFORMAT_RGB24         PixelFormat = 386930691
	PIXELFORMAT_BGR24         PixelFormat = 390076419
	PIXELFORMAT_XRGB8888      PixelFormat = 370546692
	PIXELFORMAT_RGBX8888      PixelFormat = 371595268
	PIXELFORMAT_XBGR8888      PixelFormat = 374740996
	PIXELFORMAT_BGRX8888      PixelFormat = 375789572
	PIXELFORMAT_ARGB8888      PixelFormat = 372645892
	PIXELFORMAT_RGBA8888      PixelFormat = 373694468
	PIXELFORMAT_ABGR8888      PixelFormat = 376840196
	PIXELFORMAT_BGRA8888      PixelFormat = 377888772
	PIXELFORMAT_XRGB2101010   PixelFormat = 370614276
	PIXELFORMAT_XBGR2101010   PixelFormat = 374808580
	PIXELFORMAT_ARGB2101010   PixelFormat = 372711428
	PIXELFORMAT_ABGR2101010   PixelFormat = 376905732
	PIXELFORMAT_RGB48         PixelFormat = 403714054
	PIXELFORMAT_BGR48         PixelFormat = 406859782
	PIXELFORMAT_RGBA64        PixelFormat = 404766728
	PIXELFORMAT_ARGB64        PixelFormat = 405815304
	PIXELFORMAT_BGRA64        PixelFormat = 407912456
	PIXELFORMAT_ABGR64        PixelFormat = 408961032
	PIXELFORMAT_RGB48_FLOAT   PixelFormat = 437268486
	PIXELFORMAT_BGR48_FLOAT   PixelFormat = 440414214
	PIXELFORMAT_RGBA64_FLOAT  PixelFormat = 438321160
	PIXELFORMAT_ARGB64_FLOAT  PixelFormat = 439369736
	PIXELFORMAT_BGRA64_FLOAT  PixelFormat = 441466888
	PIXELFORMAT_ABGR64_FLOAT  PixelFormat = 442515464
	PIXELFORMAT_RGB96_FLOAT   PixelFormat = 454057996
	PIXELFORMAT_BGR96_FLOAT   PixelFormat = 457203724
	PIXELFORMAT_RGBA128_FLOAT PixelFormat = 455114768
	PIXELFORMAT_ARGB128_FLOAT PixelFormat = 456163344
	PIXELFORMAT_BGRA128_FLOAT PixelFormat = 458260496
	PIXELFORMAT_ABGR128_FLOAT PixelFormat = 459309072
	PIXELFORMAT_YV12          PixelFormat = 842094169
	PIXELFORMAT_IYUV          PixelFormat = 1448433993
	PIXELFORMAT_YUY2          PixelFormat = 844715353
	PIXELFORMAT_UYVY          PixelFormat = 1498831189
	PIXELFORMAT_YVYU          PixelFormat = 1431918169
	PIXELFORMAT_NV12          PixelFormat = 842094158
	PIXELFORMAT_NV21          PixelFormat = 825382478
	PIXELFORMAT_P010          PixelFormat = 808530000
	PIXELFORMAT_EXTERNAL_OES  PixelFormat = 542328143
	PIXELFORMAT_MJPG          PixelFormat = 1196444237
	PIXELFORMAT_RGBA32        PixelFormat = 376840196
	PIXELFORMAT_ARGB32        PixelFormat = 377888772
	PIXELFORMAT_BGRA32        PixelFormat = 372645892
	PIXELFORMAT_ABGR32        PixelFormat = 373694468
	PIXELFORMAT_RGBX32        PixelFormat = 374740996
	PIXELFORMAT_XRGB32        PixelFormat = 375789572
	PIXELFORMAT_BGRX32        PixelFormat = 370546692
	PIXELFORMAT_XBGR32        PixelFormat = 371595268
)

// SDL_Colorspace - Colorspace definitions.
// (https://wiki.libsdl.org/SDL3/SDL_Colorspace)
type Colorspace uint32

const (
	COLORSPACE_UNKNOWN        Colorspace = 0
	COLORSPACE_SRGB           Colorspace = 301991328
	COLORSPACE_SRGB_LINEAR    Colorspace = 301991168
	COLORSPACE_HDR10          Colorspace = 301999616
	COLORSPACE_JPEG           Colorspace = 570426566
	COLORSPACE_BT601_LIMITED  Colorspace = 554703046
	COLORSPACE_BT601_FULL     Colorspace = 571480262
	COLORSPACE_BT709_LIMITED  Colorspace = 554697761
	COLORSPACE_BT709_FULL     Colorspace = 571474977
	COLORSPACE_BT2020_LIMITED Colorspace = 554706441
	COLORSPACE_BT2020_FULL    Colorspace = 571483657
	COLORSPACE_RGB_DEFAULT    Colorspace = 301991328
	COLORSPACE_YUV_DEFAULT    Colorspace = 570426566
)

// SDL_ScaleMode - The scaling mode.
// (https://wiki.libsdl.org/SDL3/SDL_ScaleMode)
type ScaleMode uint32

const (
	SCALEMODE_INVALID ScaleMode = 4294967295
	SCALEMODE_NEAREST ScaleMode = 0
	SCALEMODE_LINEAR  ScaleMode = 1
)

// SDL_FlipMode - The flip mode.
// (https://wiki.libsdl.org/SDL3/SDL_FlipMode)
type FlipMode uint32

const (
	FLIP_NONE       FlipMode = 0
	FLIP_HORIZONTAL FlipMode = 1
	FLIP_VERTICAL   FlipMode = 2
)

// SDL_CameraPosition - The position of camera in relation to system device.
// (https://wiki.libsdl.org/SDL3/SDL_CameraPosition)
type CameraPosition uint32

const (
	CAMERA_POSITION_UNKNOWN      CameraPosition = 0
	CAMERA_POSITION_FRONT_FACING CameraPosition = 1
	CAMERA_POSITION_BACK_FACING  CameraPosition = 2
)

// SDL_SystemTheme - System theme.
// (https://wiki.libsdl.org/SDL3/SDL_SystemTheme)
type SystemTheme uint32

const (
	SYSTEM_THEME_UNKNOWN SystemTheme = 0
	SYSTEM_THEME_LIGHT   SystemTheme = 1
	SYSTEM_THEME_DARK    SystemTheme = 2
)

// SDL_DisplayOrientation - Display orientation values; the way a display is rotated.
// (https://wiki.libsdl.org/SDL3/SDL_DisplayOrientation)
type DisplayOrientation uint32

const (
	ORIENTATION_UNKNOWN           DisplayOrientation = 0
	ORIENTATION_LANDSCAPE         DisplayOrientation = 1
	ORIENTATION_LANDSCAPE_FLIPPED DisplayOrientation = 2
	ORIENTATION_PORTRAIT          DisplayOrientation = 3
	ORIENTATION_PORTRAIT_FLIPPED  DisplayOrientation = 4
)

// SDL_FlashOperation - Window flash operation.
// (https://wiki.libsdl.org/SDL3/SDL_FlashOperation)
type FlashOperation uint32

const (
	FLASH_CANCEL        FlashOperation = 0
	FLASH_BRIEFLY       FlashOperation = 1
	FLASH_UNTIL_FOCUSED FlashOperation = 2
)

// SDL_GLAttr - An enumeration of OpenGL configuration attributes.
// (https://wiki.libsdl.org/SDL3/SDL_GLAttr)
type GLAttr uint32

const (
	GL_RED_SIZE                   GLAttr = 0
	GL_GREEN_SIZE                 GLAttr = 1
	GL_BLUE_SIZE                  GLAttr = 2
	GL_ALPHA_SIZE                 GLAttr = 3
	GL_BUFFER_SIZE                GLAttr = 4
	GL_DOUBLEBUFFER               GLAttr = 5
	GL_DEPTH_SIZE                 GLAttr = 6
	GL_STENCIL_SIZE               GLAttr = 7
	GL_ACCUM_RED_SIZE             GLAttr = 8
	GL_ACCUM_GREEN_SIZE           GLAttr = 9
	GL_ACCUM_BLUE_SIZE            GLAttr = 10
	GL_ACCUM_ALPHA_SIZE           GLAttr = 11
	GL_STEREO                     GLAttr = 12
	GL_MULTISAMPLEBUFFERS         GLAttr = 13
	GL_MULTISAMPLESAMPLES         GLAttr = 14
	GL_ACCELERATED_VISUAL         GLAttr = 15
	GL_RETAINED_BACKING           GLAttr = 16
	GL_CONTEXT_MAJOR_VERSION      GLAttr = 17
	GL_CONTEXT_MINOR_VERSION      GLAttr = 18
	GL_CONTEXT_FLAGS              GLAttr = 19
	GL_CONTEXT_PROFILE_MASK       GLAttr = 20
	GL_SHARE_WITH_CURRENT_CONTEXT GLAttr = 21
	GL_FRAMEBUFFER_SRGB_CAPABLE   GLAttr = 22
	GL_CONTEXT_RELEASE_BEHAVIOR   GLAttr = 23
	GL_CONTEXT_RESET_NOTIFICATION GLAttr = 24
	GL_CONTEXT_NO_ERROR           GLAttr = 25
	GL_FLOATBUFFERS               GLAttr = 26
	GL_EGL_PLATFORM               GLAttr = 27
)

// SDL_FileDialogType - Various types of file dialogs.
// (https://wiki.libsdl.org/SDL3/SDL_FileDialogType)
type FileDialogType uint32

const (
	FILEDIALOG_OPENFILE   FileDialogType = 0
	FILEDIALOG_SAVEFILE   FileDialogType = 1
	FILEDIALOG_OPENFOLDER FileDialogType = 2
)

// SDL_PowerState - The basic state for the system's power supply.
// (https://wiki.libsdl.org/SDL3/SDL_PowerState)
type PowerState uint32

const (
	POWERSTATE_ERROR      PowerState = 4294967295
	POWERSTATE_UNKNOWN    PowerState = 0
	POWERSTATE_ON_BATTERY PowerState = 1
	POWERSTATE_NO_BATTERY PowerState = 2
	POWERSTATE_CHARGING   PowerState = 3
	POWERSTATE_CHARGED    PowerState = 4
)

// SDL_SensorType - The different sensors defined by SDL.
// (https://wiki.libsdl.org/SDL3/SDL_SensorType)
type SensorType uint32

const (
	SENSOR_INVALID SensorType = 4294967295
	SENSOR_UNKNOWN SensorType = 0
	SENSOR_ACCEL   SensorType = 1
	SENSOR_GYRO    SensorType = 2
	SENSOR_ACCEL_L SensorType = 3
	SENSOR_GYRO_L  SensorType = 4
	SENSOR_ACCEL_R SensorType = 5
	SENSOR_GYRO_R  SensorType = 6
)

// SDL_JoystickType - An enum of some common joystick types.
// (https://wiki.libsdl.org/SDL3/SDL_JoystickType)
type JoystickType uint32

const (
	JOYSTICK_TYPE_UNKNOWN      JoystickType = 0
	JOYSTICK_TYPE_GAMEPAD      JoystickType = 1
	JOYSTICK_TYPE_WHEEL        JoystickType = 2
	JOYSTICK_TYPE_ARCADE_STICK JoystickType = 3
	JOYSTICK_TYPE_FLIGHT_STICK JoystickType = 4
	JOYSTICK_TYPE_DANCE_PAD    JoystickType = 5
	JOYSTICK_TYPE_GUITAR       JoystickType = 6
	JOYSTICK_TYPE_DRUM_KIT     JoystickType = 7
	JOYSTICK_TYPE_ARCADE_PAD   JoystickType = 8
	JOYSTICK_TYPE_THROTTLE     JoystickType = 9
	JOYSTICK_TYPE_COUNT        JoystickType = 10
)

// SDL_JoystickConnectionState - Possible connection states for a joystick device.
// (https://wiki.libsdl.org/SDL3/SDL_JoystickConnectionState)
type JoystickConnectionState uint32

const (
	JOYSTICK_CONNECTION_INVALID  JoystickConnectionState = 4294967295
	JOYSTICK_CONNECTION_UNKNOWN  JoystickConnectionState = 0
	JOYSTICK_CONNECTION_WIRED    JoystickConnectionState = 1
	JOYSTICK_CONNECTION_WIRELESS JoystickConnectionState = 2
)

// SDL_GamepadType - Standard gamepad types.
// (https://wiki.libsdl.org/SDL3/SDL_GamepadType)
type GamepadType uint32

const (
	GAMEPAD_TYPE_UNKNOWN                      GamepadType = 0
	GAMEPAD_TYPE_STANDARD                     GamepadType = 1
	GAMEPAD_TYPE_XBOX360                      GamepadType = 2
	GAMEPAD_TYPE_XBOXONE                      GamepadType = 3
	GAMEPAD_TYPE_PS3                          GamepadType = 4
	GAMEPAD_TYPE_PS4                          GamepadType = 5
	GAMEPAD_TYPE_PS5                          GamepadType = 6
	GAMEPAD_TYPE_NINTENDO_SWITCH_PRO          GamepadType = 7
	GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_LEFT  GamepadType = 8
	GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_RIGHT GamepadType = 9
	GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_PAIR  GamepadType = 10
	GAMEPAD_TYPE_COUNT                        GamepadType = 11
)

// SDL_GamepadButton - The list of buttons available on a gamepad
// (https://wiki.libsdl.org/SDL3/SDL_GamepadButton)
type GamepadButton uint32

const (
	GAMEPAD_BUTTON_INVALID        GamepadButton = 4294967295
	GAMEPAD_BUTTON_SOUTH          GamepadButton = 0
	GAMEPAD_BUTTON_EAST           GamepadButton = 1
	GAMEPAD_BUTTON_WEST           GamepadButton = 2
	GAMEPAD_BUTTON_NORTH          GamepadButton = 3
	GAMEPAD_BUTTON_BACK           GamepadButton = 4
	GAMEPAD_BUTTON_GUIDE          GamepadButton = 5
	GAMEPAD_BUTTON_START          GamepadButton = 6
	GAMEPAD_BUTTON_LEFT_STICK     GamepadButton = 7
	GAMEPAD_BUTTON_RIGHT_STICK    GamepadButton = 8
	GAMEPAD_BUTTON_LEFT_SHOULDER  GamepadButton = 9
	GAMEPAD_BUTTON_RIGHT_SHOULDER GamepadButton = 10
	GAMEPAD_BUTTON_DPAD_UP        GamepadButton = 11
	GAMEPAD_BUTTON_DPAD_DOWN      GamepadButton = 12
	GAMEPAD_BUTTON_DPAD_LEFT      GamepadButton = 13
	GAMEPAD_BUTTON_DPAD_RIGHT     GamepadButton = 14
	GAMEPAD_BUTTON_MISC1          GamepadButton = 15
	GAMEPAD_BUTTON_RIGHT_PADDLE1  GamepadButton = 16
	GAMEPAD_BUTTON_LEFT_PADDLE1   GamepadButton = 17
	GAMEPAD_BUTTON_RIGHT_PADDLE2  GamepadButton = 18
	GAMEPAD_BUTTON_LEFT_PADDLE2   GamepadButton = 19
	GAMEPAD_BUTTON_TOUCHPAD       GamepadButton = 20
	GAMEPAD_BUTTON_MISC2          GamepadButton = 21
	GAMEPAD_BUTTON_MISC3          GamepadButton = 22
	GAMEPAD_BUTTON_MISC4          GamepadButton = 23
	GAMEPAD_BUTTON_MISC5          GamepadButton = 24
	GAMEPAD_BUTTON_MISC6          GamepadButton = 25
	GAMEPAD_BUTTON_COUNT          GamepadButton = 26
)

// SDL_GamepadButtonLabel - The set of gamepad button labels
// (https://wiki.libsdl.org/SDL3/SDL_GamepadButtonLabel)
type GamepadButtonLabel uint32

const (
	GAMEPAD_BUTTON_LABEL_UNKNOWN  GamepadButtonLabel = 0
	GAMEPAD_BUTTON_LABEL_A        GamepadButtonLabel = 1
	GAMEPAD_BUTTON_LABEL_B        GamepadButtonLabel = 2
	GAMEPAD_BUTTON_LABEL_X        GamepadButtonLabel = 3
	GAMEPAD_BUTTON_LABEL_Y        GamepadButtonLabel = 4
	GAMEPAD_BUTTON_LABEL_CROSS    GamepadButtonLabel = 5
	GAMEPAD_BUTTON_LABEL_CIRCLE   GamepadButtonLabel = 6
	GAMEPAD_BUTTON_LABEL_SQUARE   GamepadButtonLabel = 7
	GAMEPAD_BUTTON_LABEL_TRIANGLE GamepadButtonLabel = 8
)

// SDL_GamepadAxis - The list of axes available on a gamepad
// (https://wiki.libsdl.org/SDL3/SDL_GamepadAxis)
type GamepadAxis uint32

const (
	GAMEPAD_AXIS_INVALID       GamepadAxis = 4294967295
	GAMEPAD_AXIS_LEFTX         GamepadAxis = 0
	GAMEPAD_AXIS_LEFTY         GamepadAxis = 1
	GAMEPAD_AXIS_RIGHTX        GamepadAxis = 2
	GAMEPAD_AXIS_RIGHTY        GamepadAxis = 3
	GAMEPAD_AXIS_LEFT_TRIGGER  GamepadAxis = 4
	GAMEPAD_AXIS_RIGHT_TRIGGER GamepadAxis = 5
	GAMEPAD_AXIS_COUNT         GamepadAxis = 6
)

// SDL_GamepadBindingType - Types of gamepad control bindings.
// (https://wiki.libsdl.org/SDL3/SDL_GamepadBindingType)
type GamepadBindingType uint32

const (
	GAMEPAD_BINDTYPE_NONE   GamepadBindingType = 0
	GAMEPAD_BINDTYPE_BUTTON GamepadBindingType = 1
	GAMEPAD_BINDTYPE_AXIS   GamepadBindingType = 2
	GAMEPAD_BINDTYPE_HAT    GamepadBindingType = 3
)

// SDL_Scancode - The SDL keyboard scancode representation.
// (https://wiki.libsdl.org/SDL3/SDL_Scancode)
type Scancode uint32

const (
	SCANCODE_UNKNOWN              Scancode = 0
	SCANCODE_A                    Scancode = 4
	SCANCODE_B                    Scancode = 5
	SCANCODE_C                    Scancode = 6
	SCANCODE_D                    Scancode = 7
	SCANCODE_E                    Scancode = 8
	SCANCODE_F                    Scancode = 9
	SCANCODE_G                    Scancode = 10
	SCANCODE_H                    Scancode = 11
	SCANCODE_I                    Scancode = 12
	SCANCODE_J                    Scancode = 13
	SCANCODE_K                    Scancode = 14
	SCANCODE_L                    Scancode = 15
	SCANCODE_M                    Scancode = 16
	SCANCODE_N                    Scancode = 17
	SCANCODE_O                    Scancode = 18
	SCANCODE_P                    Scancode = 19
	SCANCODE_Q                    Scancode = 20
	SCANCODE_R                    Scancode = 21
	SCANCODE_S                    Scancode = 22
	SCANCODE_T                    Scancode = 23
	SCANCODE_U                    Scancode = 24
	SCANCODE_V                    Scancode = 25
	SCANCODE_W                    Scancode = 26
	SCANCODE_X                    Scancode = 27
	SCANCODE_Y                    Scancode = 28
	SCANCODE_Z                    Scancode = 29
	SCANCODE_1                    Scancode = 30
	SCANCODE_2                    Scancode = 31
	SCANCODE_3                    Scancode = 32
	SCANCODE_4                    Scancode = 33
	SCANCODE_5                    Scancode = 34
	SCANCODE_6                    Scancode = 35
	SCANCODE_7                    Scancode = 36
	SCANCODE_8                    Scancode = 37
	SCANCODE_9                    Scancode = 38
	SCANCODE_0                    Scancode = 39
	SCANCODE_RETURN               Scancode = 40
	SCANCODE_ESCAPE               Scancode = 41
	SCANCODE_BACKSPACE            Scancode = 42
	SCANCODE_TAB                  Scancode = 43
	SCANCODE_SPACE                Scancode = 44
	SCANCODE_MINUS                Scancode = 45
	SCANCODE_EQUALS               Scancode = 46
	SCANCODE_LEFTBRACKET          Scancode = 47
	SCANCODE_RIGHTBRACKET         Scancode = 48
	SCANCODE_BACKSLASH            Scancode = 49
	SCANCODE_NONUSHASH            Scancode = 50
	SCANCODE_SEMICOLON            Scancode = 51
	SCANCODE_APOSTROPHE           Scancode = 52
	SCANCODE_GRAVE                Scancode = 53
	SCANCODE_COMMA                Scancode = 54
	SCANCODE_PERIOD               Scancode = 55
	SCANCODE_SLASH                Scancode = 56
	SCANCODE_CAPSLOCK             Scancode = 57
	SCANCODE_F1                   Scancode = 58
	SCANCODE_F2                   Scancode = 59
	SCANCODE_F3                   Scancode = 60
	SCANCODE_F4                   Scancode = 61
	SCANCODE_F5                   Scancode = 62
	SCANCODE_F6                   Scancode = 63
	SCANCODE_F7                   Scancode = 64
	SCANCODE_F8                   Scancode = 65
	SCANCODE_F9                   Scancode = 66
	SCANCODE_F10                  Scancode = 67
	SCANCODE_F11                  Scancode = 68
	SCANCODE_F12                  Scancode = 69
	SCANCODE_PRINTSCREEN          Scancode = 70
	SCANCODE_SCROLLLOCK           Scancode = 71
	SCANCODE_PAUSE                Scancode = 72
	SCANCODE_INSERT               Scancode = 73
	SCANCODE_HOME                 Scancode = 74
	SCANCODE_PAGEUP               Scancode = 75
	SCANCODE_DELETE               Scancode = 76
	SCANCODE_END                  Scancode = 77
	SCANCODE_PAGEDOWN             Scancode = 78
	SCANCODE_RIGHT                Scancode = 79
	SCANCODE_LEFT                 Scancode = 80
	SCANCODE_DOWN                 Scancode = 81
	SCANCODE_UP                   Scancode = 82
	SCANCODE_NUMLOCKCLEAR         Scancode = 83
	SCANCODE_KP_DIVIDE            Scancode = 84
	SCANCODE_KP_MULTIPLY          Scancode = 85
	SCANCODE_KP_MINUS             Scancode = 86
	SCANCODE_KP_PLUS              Scancode = 87
	SCANCODE_KP_ENTER             Scancode = 88
	SCANCODE_KP_1                 Scancode = 89
	SCANCODE_KP_2                 Scancode = 90
	SCANCODE_KP_3                 Scancode = 91
	SCANCODE_KP_4                 Scancode = 92
	SCANCODE_KP_5                 Scancode = 93
	SCANCODE_KP_6                 Scancode = 94
	SCANCODE_KP_7                 Scancode = 95
	SCANCODE_KP_8                 Scancode = 96
	SCANCODE_KP_9                 Scancode = 97
	SCANCODE_KP_0                 Scancode = 98
	SCANCODE_KP_PERIOD            Scancode = 99
	SCANCODE_NONUSBACKSLASH       Scancode = 100
	SCANCODE_APPLICATION          Scancode = 101
	SCANCODE_POWER                Scancode = 102
	SCANCODE_KP_EQUALS            Scancode = 103
	SCANCODE_F13                  Scancode = 104
	SCANCODE_F14                  Scancode = 105
	SCANCODE_F15                  Scancode = 106
	SCANCODE_F16                  Scancode = 107
	SCANCODE_F17                  Scancode = 108
	SCANCODE_F18                  Scancode = 109
	SCANCODE_F19                  Scancode = 110
	SCANCODE_F20                  Scancode = 111
	SCANCODE_F21                  Scancode = 112
	SCANCODE_F22                  Scancode = 113
	SCANCODE_F23                  Scancode = 114
	SCANCODE_F24                  Scancode = 115
	SCANCODE_EXECUTE              Scancode = 116
	SCANCODE_HELP                 Scancode = 117
	SCANCODE_MENU                 Scancode = 118
	SCANCODE_SELECT               Scancode = 119
	SCANCODE_STOP                 Scancode = 120
	SCANCODE_AGAIN                Scancode = 121
	SCANCODE_UNDO                 Scancode = 122
	SCANCODE_CUT                  Scancode = 123
	SCANCODE_COPY                 Scancode = 124
	SCANCODE_PASTE                Scancode = 125
	SCANCODE_FIND                 Scancode = 126
	SCANCODE_MUTE                 Scancode = 127
	SCANCODE_VOLUMEUP             Scancode = 128
	SCANCODE_VOLUMEDOWN           Scancode = 129
	SCANCODE_KP_COMMA             Scancode = 133
	SCANCODE_KP_EQUALSAS400       Scancode = 134
	SCANCODE_INTERNATIONAL1       Scancode = 135
	SCANCODE_INTERNATIONAL2       Scancode = 136
	SCANCODE_INTERNATIONAL3       Scancode = 137
	SCANCODE_INTERNATIONAL4       Scancode = 138
	SCANCODE_INTERNATIONAL5       Scancode = 139
	SCANCODE_INTERNATIONAL6       Scancode = 140
	SCANCODE_INTERNATIONAL7       Scancode = 141
	SCANCODE_INTERNATIONAL8       Scancode = 142
	SCANCODE_INTERNATIONAL9       Scancode = 143
	SCANCODE_LANG1                Scancode = 144
	SCANCODE_LANG2                Scancode = 145
	SCANCODE_LANG3                Scancode = 146
	SCANCODE_LANG4                Scancode = 147
	SCANCODE_LANG5                Scancode = 148
	SCANCODE_LANG6                Scancode = 149
	SCANCODE_LANG7                Scancode = 150
	SCANCODE_LANG8                Scancode = 151
	SCANCODE_LANG9                Scancode = 152
	SCANCODE_ALTERASE             Scancode = 153
	SCANCODE_SYSREQ               Scancode = 154
	SCANCODE_CANCEL               Scancode = 155
	SCANCODE_CLEAR                Scancode = 156
	SCANCODE_PRIOR                Scancode = 157
	SCANCODE_RETURN2              Scancode = 158
	SCANCODE_SEPARATOR            Scancode = 159
	SCANCODE_OUT                  Scancode = 160
	SCANCODE_OPER                 Scancode = 161
	SCANCODE_CLEARAGAIN           Scancode = 162
	SCANCODE_CRSEL                Scancode = 163
	SCANCODE_EXSEL                Scancode = 164
	SCANCODE_KP_00                Scancode = 176
	SCANCODE_KP_000               Scancode = 177
	SCANCODE_THOUSANDSSEPARATOR   Scancode = 178
	SCANCODE_DECIMALSEPARATOR     Scancode = 179
	SCANCODE_CURRENCYUNIT         Scancode = 180
	SCANCODE_CURRENCYSUBUNIT      Scancode = 181
	SCANCODE_KP_LEFTPAREN         Scancode = 182
	SCANCODE_KP_RIGHTPAREN        Scancode = 183
	SCANCODE_KP_LEFTBRACE         Scancode = 184
	SCANCODE_KP_RIGHTBRACE        Scancode = 185
	SCANCODE_KP_TAB               Scancode = 186
	SCANCODE_KP_BACKSPACE         Scancode = 187
	SCANCODE_KP_A                 Scancode = 188
	SCANCODE_KP_B                 Scancode = 189
	SCANCODE_KP_C                 Scancode = 190
	SCANCODE_KP_D                 Scancode = 191
	SCANCODE_KP_E                 Scancode = 192
	SCANCODE_KP_F                 Scancode = 193
	SCANCODE_KP_XOR               Scancode = 194
	SCANCODE_KP_POWER             Scancode = 195
	SCANCODE_KP_PERCENT           Scancode = 196
	SCANCODE_KP_LESS              Scancode = 197
	SCANCODE_KP_GREATER           Scancode = 198
	SCANCODE_KP_AMPERSAND         Scancode = 199
	SCANCODE_KP_DBLAMPERSAND      Scancode = 200
	SCANCODE_KP_VERTICALBAR       Scancode = 201
	SCANCODE_KP_DBLVERTICALBAR    Scancode = 202
	SCANCODE_KP_COLON             Scancode = 203
	SCANCODE_KP_HASH              Scancode = 204
	SCANCODE_KP_SPACE             Scancode = 205
	SCANCODE_KP_AT                Scancode = 206
	SCANCODE_KP_EXCLAM            Scancode = 207
	SCANCODE_KP_MEMSTORE          Scancode = 208
	SCANCODE_KP_MEMRECALL         Scancode = 209
	SCANCODE_KP_MEMCLEAR          Scancode = 210
	SCANCODE_KP_MEMADD            Scancode = 211
	SCANCODE_KP_MEMSUBTRACT       Scancode = 212
	SCANCODE_KP_MEMMULTIPLY       Scancode = 213
	SCANCODE_KP_MEMDIVIDE         Scancode = 214
	SCANCODE_KP_PLUSMINUS         Scancode = 215
	SCANCODE_KP_CLEAR             Scancode = 216
	SCANCODE_KP_CLEARENTRY        Scancode = 217
	SCANCODE_KP_BINARY            Scancode = 218
	SCANCODE_KP_OCTAL             Scancode = 219
	SCANCODE_KP_DECIMAL           Scancode = 220
	SCANCODE_KP_HEXADECIMAL       Scancode = 221
	SCANCODE_LCTRL                Scancode = 224
	SCANCODE_LSHIFT               Scancode = 225
	SCANCODE_LALT                 Scancode = 226
	SCANCODE_LGUI                 Scancode = 227
	SCANCODE_RCTRL                Scancode = 228
	SCANCODE_RSHIFT               Scancode = 229
	SCANCODE_RALT                 Scancode = 230
	SCANCODE_RGUI                 Scancode = 231
	SCANCODE_MODE                 Scancode = 257
	SCANCODE_SLEEP                Scancode = 258
	SCANCODE_WAKE                 Scancode = 259
	SCANCODE_CHANNEL_INCREMENT    Scancode = 260
	SCANCODE_CHANNEL_DECREMENT    Scancode = 261
	SCANCODE_MEDIA_PLAY           Scancode = 262
	SCANCODE_MEDIA_PAUSE          Scancode = 263
	SCANCODE_MEDIA_RECORD         Scancode = 264
	SCANCODE_MEDIA_FAST_FORWARD   Scancode = 265
	SCANCODE_MEDIA_REWIND         Scancode = 266
	SCANCODE_MEDIA_NEXT_TRACK     Scancode = 267
	SCANCODE_MEDIA_PREVIOUS_TRACK Scancode = 268
	SCANCODE_MEDIA_STOP           Scancode = 269
	SCANCODE_MEDIA_EJECT          Scancode = 270
	SCANCODE_MEDIA_PLAY_PAUSE     Scancode = 271
	SCANCODE_MEDIA_SELECT         Scancode = 272
	SCANCODE_AC_NEW               Scancode = 273
	SCANCODE_AC_OPEN              Scancode = 274
	SCANCODE_AC_CLOSE             Scancode = 275
	SCANCODE_AC_EXIT              Scancode = 276
	SCANCODE_AC_SAVE              Scancode = 277
	SCANCODE_AC_PRINT             Scancode = 278
	SCANCODE_AC_PROPERTIES        Scancode = 279
	SCANCODE_AC_SEARCH            Scancode = 280
	SCANCODE_AC_HOME              Scancode = 281
	SCANCODE_AC_BACK              Scancode = 282
	SCANCODE_AC_FORWARD           Scancode = 283
	SCANCODE_AC_STOP              Scancode = 284
	SCANCODE_AC_REFRESH           Scancode = 285
	SCANCODE_AC_BOOKMARKS         Scancode = 286
	SCANCODE_SOFTLEFT             Scancode = 287
	SCANCODE_SOFTRIGHT            Scancode = 288
	SCANCODE_CALL                 Scancode = 289
	SCANCODE_ENDCALL              Scancode = 290
	SCANCODE_RESERVED             Scancode = 400
	SCANCODE_COUNT                Scancode = 512
)

// SDL_SystemCursor - Cursor types for [SDL_CreateSystemCursor](SDL_CreateSystemCursor)().
// (https://wiki.libsdl.org/SDL3/SDL_SystemCursor)
type SystemCursor uint32

const (
	SYSTEM_CURSOR_DEFAULT     SystemCursor = 0
	SYSTEM_CURSOR_TEXT        SystemCursor = 1
	SYSTEM_CURSOR_WAIT        SystemCursor = 2
	SYSTEM_CURSOR_CROSSHAIR   SystemCursor = 3
	SYSTEM_CURSOR_PROGRESS    SystemCursor = 4
	SYSTEM_CURSOR_NWSE_RESIZE SystemCursor = 5
	SYSTEM_CURSOR_NESW_RESIZE SystemCursor = 6
	SYSTEM_CURSOR_EW_RESIZE   SystemCursor = 7
	SYSTEM_CURSOR_NS_RESIZE   SystemCursor = 8
	SYSTEM_CURSOR_MOVE        SystemCursor = 9
	SYSTEM_CURSOR_NOT_ALLOWED SystemCursor = 10
	SYSTEM_CURSOR_POINTER     SystemCursor = 11
	SYSTEM_CURSOR_NW_RESIZE   SystemCursor = 12
	SYSTEM_CURSOR_N_RESIZE    SystemCursor = 13
	SYSTEM_CURSOR_NE_RESIZE   SystemCursor = 14
	SYSTEM_CURSOR_E_RESIZE    SystemCursor = 15
	SYSTEM_CURSOR_SE_RESIZE   SystemCursor = 16
	SYSTEM_CURSOR_S_RESIZE    SystemCursor = 17
	SYSTEM_CURSOR_SW_RESIZE   SystemCursor = 18
	SYSTEM_CURSOR_W_RESIZE    SystemCursor = 19
	SYSTEM_CURSOR_COUNT       SystemCursor = 20
)

// SDL_MouseWheelDirection - Scroll direction types for the Scroll event
// (https://wiki.libsdl.org/SDL3/SDL_MouseWheelDirection)
type MouseWheelDirection uint32

const (
	MOUSEWHEEL_NORMAL  MouseWheelDirection = 0
	MOUSEWHEEL_FLIPPED MouseWheelDirection = 1
)

// SDL_TouchDeviceType - An enum that describes the type of a touch device.
// (https://wiki.libsdl.org/SDL3/SDL_TouchDeviceType)
type TouchDeviceType uint32

const (
	TOUCH_DEVICE_INVALID           TouchDeviceType = 4294967295
	TOUCH_DEVICE_DIRECT            TouchDeviceType = 0
	TOUCH_DEVICE_INDIRECT_ABSOLUTE TouchDeviceType = 1
	TOUCH_DEVICE_INDIRECT_RELATIVE TouchDeviceType = 2
)

// SDL_PenAxis - Pen axis indices.
// (https://wiki.libsdl.org/SDL3/SDL_PenAxis)
type PenAxis uint32

const (
	PEN_AXIS_PRESSURE            PenAxis = 0
	PEN_AXIS_XTILT               PenAxis = 1
	PEN_AXIS_YTILT               PenAxis = 2
	PEN_AXIS_DISTANCE            PenAxis = 3
	PEN_AXIS_ROTATION            PenAxis = 4
	PEN_AXIS_SLIDER              PenAxis = 5
	PEN_AXIS_TANGENTIAL_PRESSURE PenAxis = 6
	PEN_AXIS_COUNT               PenAxis = 7
)

// SDL_EventType - The types of events that can be delivered.
// (https://wiki.libsdl.org/SDL3/SDL_EventType)
type EventType uint32

const (
	EVENT_FIRST                         EventType = 0
	EVENT_QUIT                          EventType = 256
	EVENT_TERMINATING                   EventType = 257
	EVENT_LOW_MEMORY                    EventType = 258
	EVENT_WILL_ENTER_BACKGROUND         EventType = 259
	EVENT_DID_ENTER_BACKGROUND          EventType = 260
	EVENT_WILL_ENTER_FOREGROUND         EventType = 261
	EVENT_DID_ENTER_FOREGROUND          EventType = 262
	EVENT_LOCALE_CHANGED                EventType = 263
	EVENT_SYSTEM_THEME_CHANGED          EventType = 264
	EVENT_DISPLAY_ORIENTATION           EventType = 337
	EVENT_DISPLAY_ADDED                 EventType = 338
	EVENT_DISPLAY_REMOVED               EventType = 339
	EVENT_DISPLAY_MOVED                 EventType = 340
	EVENT_DISPLAY_DESKTOP_MODE_CHANGED  EventType = 341
	EVENT_DISPLAY_CURRENT_MODE_CHANGED  EventType = 342
	EVENT_DISPLAY_CONTENT_SCALE_CHANGED EventType = 343
	EVENT_DISPLAY_FIRST                 EventType = 337
	EVENT_DISPLAY_LAST                  EventType = 343
	EVENT_WINDOW_SHOWN                  EventType = 514
	EVENT_WINDOW_HIDDEN                 EventType = 515
	EVENT_WINDOW_EXPOSED                EventType = 516
	EVENT_WINDOW_MOVED                  EventType = 517
	EVENT_WINDOW_RESIZED                EventType = 518
	EVENT_WINDOW_PIXEL_SIZE_CHANGED     EventType = 519
	EVENT_WINDOW_METAL_VIEW_RESIZED     EventType = 520
	EVENT_WINDOW_MINIMIZED              EventType = 521
	EVENT_WINDOW_MAXIMIZED              EventType = 522
	EVENT_WINDOW_RESTORED               EventType = 523
	EVENT_WINDOW_MOUSE_ENTER            EventType = 524
	EVENT_WINDOW_MOUSE_LEAVE            EventType = 525
	EVENT_WINDOW_FOCUS_GAINED           EventType = 526
	EVENT_WINDOW_FOCUS_LOST             EventType = 527
	EVENT_WINDOW_CLOSE_REQUESTED        EventType = 528
	EVENT_WINDOW_HIT_TEST               EventType = 529
	EVENT_WINDOW_ICCPROF_CHANGED        EventType = 530
	EVENT_WINDOW_DISPLAY_CHANGED        EventType = 531
	EVENT_WINDOW_DISPLAY_SCALE_CHANGED  EventType = 532
	EVENT_WINDOW_SAFE_AREA_CHANGED      EventType = 533
	EVENT_WINDOW_OCCLUDED               EventType = 534
	EVENT_WINDOW_ENTER_FULLSCREEN       EventType = 535
	EVENT_WINDOW_LEAVE_FULLSCREEN       EventType = 536
	EVENT_WINDOW_DESTROYED              EventType = 537
	EVENT_WINDOW_HDR_STATE_CHANGED      EventType = 538
	EVENT_WINDOW_FIRST                  EventType = 514
	EVENT_WINDOW_LAST                   EventType = 538
	EVENT_KEY_DOWN                      EventType = 768
	EVENT_KEY_UP                        EventType = 769
	EVENT_TEXT_EDITING                  EventType = 770
	EVENT_TEXT_INPUT                    EventType = 771
	EVENT_KEYMAP_CHANGED                EventType = 772
	EVENT_KEYBOARD_ADDED                EventType = 773
	EVENT_KEYBOARD_REMOVED              EventType = 774
	EVENT_TEXT_EDITING_CANDIDATES       EventType = 775
	EVENT_MOUSE_MOTION                  EventType = 1024
	EVENT_MOUSE_BUTTON_DOWN             EventType = 1025
	EVENT_MOUSE_BUTTON_UP               EventType = 1026
	EVENT_MOUSE_WHEEL                   EventType = 1027
	EVENT_MOUSE_ADDED                   EventType = 1028
	EVENT_MOUSE_REMOVED                 EventType = 1029
	EVENT_JOYSTICK_AXIS_MOTION          EventType = 1536
	EVENT_JOYSTICK_BALL_MOTION          EventType = 1537
	EVENT_JOYSTICK_HAT_MOTION           EventType = 1538
	EVENT_JOYSTICK_BUTTON_DOWN          EventType = 1539
	EVENT_JOYSTICK_BUTTON_UP            EventType = 1540
	EVENT_JOYSTICK_ADDED                EventType = 1541
	EVENT_JOYSTICK_REMOVED              EventType = 1542
	EVENT_JOYSTICK_BATTERY_UPDATED      EventType = 1543
	EVENT_JOYSTICK_UPDATE_COMPLETE      EventType = 1544
	EVENT_GAMEPAD_AXIS_MOTION           EventType = 1616
	EVENT_GAMEPAD_BUTTON_DOWN           EventType = 1617
	EVENT_GAMEPAD_BUTTON_UP             EventType = 1618
	EVENT_GAMEPAD_ADDED                 EventType = 1619
	EVENT_GAMEPAD_REMOVED               EventType = 1620
	EVENT_GAMEPAD_REMAPPED              EventType = 1621
	EVENT_GAMEPAD_TOUCHPAD_DOWN         EventType = 1622
	EVENT_GAMEPAD_TOUCHPAD_MOTION       EventType = 1623
	EVENT_GAMEPAD_TOUCHPAD_UP           EventType = 1624
	EVENT_GAMEPAD_SENSOR_UPDATE         EventType = 1625
	EVENT_GAMEPAD_UPDATE_COMPLETE       EventType = 1626
	EVENT_GAMEPAD_STEAM_HANDLE_UPDATED  EventType = 1627
	EVENT_FINGER_DOWN                   EventType = 1792
	EVENT_FINGER_UP                     EventType = 1793
	EVENT_FINGER_MOTION                 EventType = 1794
	EVENT_FINGER_CANCELED               EventType = 1795
	EVENT_CLIPBOARD_UPDATE              EventType = 2304
	EVENT_DROP_FILE                     EventType = 4096
	EVENT_DROP_TEXT                     EventType = 4097
	EVENT_DROP_BEGIN                    EventType = 4098
	EVENT_DROP_COMPLETE                 EventType = 4099
	EVENT_DROP_POSITION                 EventType = 4100
	EVENT_AUDIO_DEVICE_ADDED            EventType = 4352
	EVENT_AUDIO_DEVICE_REMOVED          EventType = 4353
	EVENT_AUDIO_DEVICE_FORMAT_CHANGED   EventType = 4354
	EVENT_SENSOR_UPDATE                 EventType = 4608
	EVENT_PEN_PROXIMITY_IN              EventType = 4864
	EVENT_PEN_PROXIMITY_OUT             EventType = 4865
	EVENT_PEN_DOWN                      EventType = 4866
	EVENT_PEN_UP                        EventType = 4867
	EVENT_PEN_BUTTON_DOWN               EventType = 4868
	EVENT_PEN_BUTTON_UP                 EventType = 4869
	EVENT_PEN_MOTION                    EventType = 4870
	EVENT_PEN_AXIS                      EventType = 4871
	EVENT_CAMERA_DEVICE_ADDED           EventType = 5120
	EVENT_CAMERA_DEVICE_REMOVED         EventType = 5121
	EVENT_CAMERA_DEVICE_APPROVED        EventType = 5122
	EVENT_CAMERA_DEVICE_DENIED          EventType = 5123
	EVENT_RENDER_TARGETS_RESET          EventType = 8192
	EVENT_RENDER_DEVICE_RESET           EventType = 8193
	EVENT_RENDER_DEVICE_LOST            EventType = 8194
	EVENT_PRIVATE0                      EventType = 16384
	EVENT_PRIVATE1                      EventType = 16385
	EVENT_PRIVATE2                      EventType = 16386
	EVENT_PRIVATE3                      EventType = 16387
	EVENT_POLL_SENTINEL                 EventType = 32512
	EVENT_USER                          EventType = 32768
	EVENT_LAST                          EventType = 65535
	EVENT_ENUM_PADDING                  EventType = 2147483647
)

// SDL_EventAction - The type of action to request from [SDL_PeepEvents](SDL_PeepEvents)().
// (https://wiki.libsdl.org/SDL3/SDL_EventAction)
type EventAction uint32

const (
	ADDEVENT  EventAction = 0
	PEEKEVENT EventAction = 1
	GETEVENT  EventAction = 2
)

// SDL_Folder - The type of the OS-provided default folder for a specific purpose.
// (https://wiki.libsdl.org/SDL3/SDL_Folder)
type Folder uint32

const (
	FOLDER_HOME        Folder = 0
	FOLDER_DESKTOP     Folder = 1
	FOLDER_DOCUMENTS   Folder = 2
	FOLDER_DOWNLOADS   Folder = 3
	FOLDER_MUSIC       Folder = 4
	FOLDER_PICTURES    Folder = 5
	FOLDER_PUBLICSHARE Folder = 6
	FOLDER_SAVEDGAMES  Folder = 7
	FOLDER_SCREENSHOTS Folder = 8
	FOLDER_TEMPLATES   Folder = 9
	FOLDER_VIDEOS      Folder = 10
	FOLDER_COUNT       Folder = 11
)

// SDL_PathType - Types of filesystem entries.
// (https://wiki.libsdl.org/SDL3/SDL_PathType)
type PathType uint32

const (
	PATHTYPE_NONE      PathType = 0
	PATHTYPE_FILE      PathType = 1
	PATHTYPE_DIRECTORY PathType = 2
	PATHTYPE_OTHER     PathType = 3
)

// SDL_GPUPrimitiveType - Specifies the primitive topology of a graphics pipeline.
// (https://wiki.libsdl.org/SDL3/SDL_GPUPrimitiveType)
type GPUPrimitiveType uint32

const (
	GPU_PRIMITIVETYPE_TRIANGLELIST  GPUPrimitiveType = 0
	GPU_PRIMITIVETYPE_TRIANGLESTRIP GPUPrimitiveType = 1
	GPU_PRIMITIVETYPE_LINELIST      GPUPrimitiveType = 2
	GPU_PRIMITIVETYPE_LINESTRIP     GPUPrimitiveType = 3
	GPU_PRIMITIVETYPE_POINTLIST     GPUPrimitiveType = 4
)

// SDL_GPULoadOp - Specifies how the contents of a texture attached to a render pass are treated at the beginning of the render pass.
// (https://wiki.libsdl.org/SDL3/SDL_GPULoadOp)
type GPULoadOp uint32

const (
	GPU_LOADOP_LOAD      GPULoadOp = 0
	GPU_LOADOP_CLEAR     GPULoadOp = 1
	GPU_LOADOP_DONT_CARE GPULoadOp = 2
)

// SDL_GPUStoreOp - Specifies how the contents of a texture attached to a render pass are treated at the end of the render pass.
// (https://wiki.libsdl.org/SDL3/SDL_GPUStoreOp)
type GPUStoreOp uint32

const (
	GPU_STOREOP_STORE             GPUStoreOp = 0
	GPU_STOREOP_DONT_CARE         GPUStoreOp = 1
	GPU_STOREOP_RESOLVE           GPUStoreOp = 2
	GPU_STOREOP_RESOLVE_AND_STORE GPUStoreOp = 3
)

// SDL_GPUIndexElementSize - Specifies the size of elements in an index buffer.
// (https://wiki.libsdl.org/SDL3/SDL_GPUIndexElementSize)
type GPUIndexElementSize uint32

const (
	GPU_INDEXELEMENTSIZE_16BIT GPUIndexElementSize = 0
	GPU_INDEXELEMENTSIZE_32BIT GPUIndexElementSize = 1
)

// SDL_GPUTextureFormat - Specifies the pixel format of a texture.
// (https://wiki.libsdl.org/SDL3/SDL_GPUTextureFormat)
type GPUTextureFormat uint32

const (
	GPU_TEXTUREFORMAT_INVALID               GPUTextureFormat = 0
	GPU_TEXTUREFORMAT_A8_UNORM              GPUTextureFormat = 1
	GPU_TEXTUREFORMAT_R8_UNORM              GPUTextureFormat = 2
	GPU_TEXTUREFORMAT_R8G8_UNORM            GPUTextureFormat = 3
	GPU_TEXTUREFORMAT_R8G8B8A8_UNORM        GPUTextureFormat = 4
	GPU_TEXTUREFORMAT_R16_UNORM             GPUTextureFormat = 5
	GPU_TEXTUREFORMAT_R16G16_UNORM          GPUTextureFormat = 6
	GPU_TEXTUREFORMAT_R16G16B16A16_UNORM    GPUTextureFormat = 7
	GPU_TEXTUREFORMAT_R10G10B10A2_UNORM     GPUTextureFormat = 8
	GPU_TEXTUREFORMAT_B5G6R5_UNORM          GPUTextureFormat = 9
	GPU_TEXTUREFORMAT_B5G5R5A1_UNORM        GPUTextureFormat = 10
	GPU_TEXTUREFORMAT_B4G4R4A4_UNORM        GPUTextureFormat = 11
	GPU_TEXTUREFORMAT_B8G8R8A8_UNORM        GPUTextureFormat = 12
	GPU_TEXTUREFORMAT_BC1_RGBA_UNORM        GPUTextureFormat = 13
	GPU_TEXTUREFORMAT_BC2_RGBA_UNORM        GPUTextureFormat = 14
	GPU_TEXTUREFORMAT_BC3_RGBA_UNORM        GPUTextureFormat = 15
	GPU_TEXTUREFORMAT_BC4_R_UNORM           GPUTextureFormat = 16
	GPU_TEXTUREFORMAT_BC5_RG_UNORM          GPUTextureFormat = 17
	GPU_TEXTUREFORMAT_BC7_RGBA_UNORM        GPUTextureFormat = 18
	GPU_TEXTUREFORMAT_BC6H_RGB_FLOAT        GPUTextureFormat = 19
	GPU_TEXTUREFORMAT_BC6H_RGB_UFLOAT       GPUTextureFormat = 20
	GPU_TEXTUREFORMAT_R8_SNORM              GPUTextureFormat = 21
	GPU_TEXTUREFORMAT_R8G8_SNORM            GPUTextureFormat = 22
	GPU_TEXTUREFORMAT_R8G8B8A8_SNORM        GPUTextureFormat = 23
	GPU_TEXTUREFORMAT_R16_SNORM             GPUTextureFormat = 24
	GPU_TEXTUREFORMAT_R16G16_SNORM          GPUTextureFormat = 25
	GPU_TEXTUREFORMAT_R16G16B16A16_SNORM    GPUTextureFormat = 26
	GPU_TEXTUREFORMAT_R16_FLOAT             GPUTextureFormat = 27
	GPU_TEXTUREFORMAT_R16G16_FLOAT          GPUTextureFormat = 28
	GPU_TEXTUREFORMAT_R16G16B16A16_FLOAT    GPUTextureFormat = 29
	GPU_TEXTUREFORMAT_R32_FLOAT             GPUTextureFormat = 30
	GPU_TEXTUREFORMAT_R32G32_FLOAT          GPUTextureFormat = 31
	GPU_TEXTUREFORMAT_R32G32B32A32_FLOAT    GPUTextureFormat = 32
	GPU_TEXTUREFORMAT_R11G11B10_UFLOAT      GPUTextureFormat = 33
	GPU_TEXTUREFORMAT_R8_UINT               GPUTextureFormat = 34
	GPU_TEXTUREFORMAT_R8G8_UINT             GPUTextureFormat = 35
	GPU_TEXTUREFORMAT_R8G8B8A8_UINT         GPUTextureFormat = 36
	GPU_TEXTUREFORMAT_R16_UINT              GPUTextureFormat = 37
	GPU_TEXTUREFORMAT_R16G16_UINT           GPUTextureFormat = 38
	GPU_TEXTUREFORMAT_R16G16B16A16_UINT     GPUTextureFormat = 39
	GPU_TEXTUREFORMAT_R32_UINT              GPUTextureFormat = 40
	GPU_TEXTUREFORMAT_R32G32_UINT           GPUTextureFormat = 41
	GPU_TEXTUREFORMAT_R32G32B32A32_UINT     GPUTextureFormat = 42
	GPU_TEXTUREFORMAT_R8_INT                GPUTextureFormat = 43
	GPU_TEXTUREFORMAT_R8G8_INT              GPUTextureFormat = 44
	GPU_TEXTUREFORMAT_R8G8B8A8_INT          GPUTextureFormat = 45
	GPU_TEXTUREFORMAT_R16_INT               GPUTextureFormat = 46
	GPU_TEXTUREFORMAT_R16G16_INT            GPUTextureFormat = 47
	GPU_TEXTUREFORMAT_R16G16B16A16_INT      GPUTextureFormat = 48
	GPU_TEXTUREFORMAT_R32_INT               GPUTextureFormat = 49
	GPU_TEXTUREFORMAT_R32G32_INT            GPUTextureFormat = 50
	GPU_TEXTUREFORMAT_R32G32B32A32_INT      GPUTextureFormat = 51
	GPU_TEXTUREFORMAT_R8G8B8A8_UNORM_SRGB   GPUTextureFormat = 52
	GPU_TEXTUREFORMAT_B8G8R8A8_UNORM_SRGB   GPUTextureFormat = 53
	GPU_TEXTUREFORMAT_BC1_RGBA_UNORM_SRGB   GPUTextureFormat = 54
	GPU_TEXTUREFORMAT_BC2_RGBA_UNORM_SRGB   GPUTextureFormat = 55
	GPU_TEXTUREFORMAT_BC3_RGBA_UNORM_SRGB   GPUTextureFormat = 56
	GPU_TEXTUREFORMAT_BC7_RGBA_UNORM_SRGB   GPUTextureFormat = 57
	GPU_TEXTUREFORMAT_D16_UNORM             GPUTextureFormat = 58
	GPU_TEXTUREFORMAT_D24_UNORM             GPUTextureFormat = 59
	GPU_TEXTUREFORMAT_D32_FLOAT             GPUTextureFormat = 60
	GPU_TEXTUREFORMAT_D24_UNORM_S8_UINT     GPUTextureFormat = 61
	GPU_TEXTUREFORMAT_D32_FLOAT_S8_UINT     GPUTextureFormat = 62
	GPU_TEXTUREFORMAT_ASTC_4x4_UNORM        GPUTextureFormat = 63
	GPU_TEXTUREFORMAT_ASTC_5x4_UNORM        GPUTextureFormat = 64
	GPU_TEXTUREFORMAT_ASTC_5x5_UNORM        GPUTextureFormat = 65
	GPU_TEXTUREFORMAT_ASTC_6x5_UNORM        GPUTextureFormat = 66
	GPU_TEXTUREFORMAT_ASTC_6x6_UNORM        GPUTextureFormat = 67
	GPU_TEXTUREFORMAT_ASTC_8x5_UNORM        GPUTextureFormat = 68
	GPU_TEXTUREFORMAT_ASTC_8x6_UNORM        GPUTextureFormat = 69
	GPU_TEXTUREFORMAT_ASTC_8x8_UNORM        GPUTextureFormat = 70
	GPU_TEXTUREFORMAT_ASTC_10x5_UNORM       GPUTextureFormat = 71
	GPU_TEXTUREFORMAT_ASTC_10x6_UNORM       GPUTextureFormat = 72
	GPU_TEXTUREFORMAT_ASTC_10x8_UNORM       GPUTextureFormat = 73
	GPU_TEXTUREFORMAT_ASTC_10x10_UNORM      GPUTextureFormat = 74
	GPU_TEXTUREFORMAT_ASTC_12x10_UNORM      GPUTextureFormat = 75
	GPU_TEXTUREFORMAT_ASTC_12x12_UNORM      GPUTextureFormat = 76
	GPU_TEXTUREFORMAT_ASTC_4x4_UNORM_SRGB   GPUTextureFormat = 77
	GPU_TEXTUREFORMAT_ASTC_5x4_UNORM_SRGB   GPUTextureFormat = 78
	GPU_TEXTUREFORMAT_ASTC_5x5_UNORM_SRGB   GPUTextureFormat = 79
	GPU_TEXTUREFORMAT_ASTC_6x5_UNORM_SRGB   GPUTextureFormat = 80
	GPU_TEXTUREFORMAT_ASTC_6x6_UNORM_SRGB   GPUTextureFormat = 81
	GPU_TEXTUREFORMAT_ASTC_8x5_UNORM_SRGB   GPUTextureFormat = 82
	GPU_TEXTUREFORMAT_ASTC_8x6_UNORM_SRGB   GPUTextureFormat = 83
	GPU_TEXTUREFORMAT_ASTC_8x8_UNORM_SRGB   GPUTextureFormat = 84
	GPU_TEXTUREFORMAT_ASTC_10x5_UNORM_SRGB  GPUTextureFormat = 85
	GPU_TEXTUREFORMAT_ASTC_10x6_UNORM_SRGB  GPUTextureFormat = 86
	GPU_TEXTUREFORMAT_ASTC_10x8_UNORM_SRGB  GPUTextureFormat = 87
	GPU_TEXTUREFORMAT_ASTC_10x10_UNORM_SRGB GPUTextureFormat = 88
	GPU_TEXTUREFORMAT_ASTC_12x10_UNORM_SRGB GPUTextureFormat = 89
	GPU_TEXTUREFORMAT_ASTC_12x12_UNORM_SRGB GPUTextureFormat = 90
	GPU_TEXTUREFORMAT_ASTC_4x4_FLOAT        GPUTextureFormat = 91
	GPU_TEXTUREFORMAT_ASTC_5x4_FLOAT        GPUTextureFormat = 92
	GPU_TEXTUREFORMAT_ASTC_5x5_FLOAT        GPUTextureFormat = 93
	GPU_TEXTUREFORMAT_ASTC_6x5_FLOAT        GPUTextureFormat = 94
	GPU_TEXTUREFORMAT_ASTC_6x6_FLOAT        GPUTextureFormat = 95
	GPU_TEXTUREFORMAT_ASTC_8x5_FLOAT        GPUTextureFormat = 96
	GPU_TEXTUREFORMAT_ASTC_8x6_FLOAT        GPUTextureFormat = 97
	GPU_TEXTUREFORMAT_ASTC_8x8_FLOAT        GPUTextureFormat = 98
	GPU_TEXTUREFORMAT_ASTC_10x5_FLOAT       GPUTextureFormat = 99
	GPU_TEXTUREFORMAT_ASTC_10x6_FLOAT       GPUTextureFormat = 100
	GPU_TEXTUREFORMAT_ASTC_10x8_FLOAT       GPUTextureFormat = 101
	GPU_TEXTUREFORMAT_ASTC_10x10_FLOAT      GPUTextureFormat = 102
	GPU_TEXTUREFORMAT_ASTC_12x10_FLOAT      GPUTextureFormat = 103
	GPU_TEXTUREFORMAT_ASTC_12x12_FLOAT      GPUTextureFormat = 104
)

// SDL_GPUTextureType - Specifies the type of a texture.
// (https://wiki.libsdl.org/SDL3/SDL_GPUTextureType)
type GPUTextureType uint32

const (
	GPU_TEXTURETYPE_2D         GPUTextureType = 0
	GPU_TEXTURETYPE_2D_ARRAY   GPUTextureType = 1
	GPU_TEXTURETYPE_3D         GPUTextureType = 2
	GPU_TEXTURETYPE_CUBE       GPUTextureType = 3
	GPU_TEXTURETYPE_CUBE_ARRAY GPUTextureType = 4
)

// SDL_GPUSampleCount - Specifies the sample count of a texture.
// (https://wiki.libsdl.org/SDL3/SDL_GPUSampleCount)
type GPUSampleCount uint32

const (
	GPU_SAMPLECOUNT_1 GPUSampleCount = 0
	GPU_SAMPLECOUNT_2 GPUSampleCount = 1
	GPU_SAMPLECOUNT_4 GPUSampleCount = 2
	GPU_SAMPLECOUNT_8 GPUSampleCount = 3
)

// SDL_GPUTransferBufferUsage - Specifies how a transfer buffer is intended to be used by the client.
// (https://wiki.libsdl.org/SDL3/SDL_GPUTransferBufferUsage)
type GPUTransferBufferUsage uint32

const (
	GPU_TRANSFERBUFFERUSAGE_UPLOAD   GPUTransferBufferUsage = 0
	GPU_TRANSFERBUFFERUSAGE_DOWNLOAD GPUTransferBufferUsage = 1
)

// SDL_GPUShaderStage - Specifies which stage a shader program corresponds to.
// (https://wiki.libsdl.org/SDL3/SDL_GPUShaderStage)
type GPUShaderStage uint32

const (
	GPU_SHADERSTAGE_VERTEX   GPUShaderStage = 0
	GPU_SHADERSTAGE_FRAGMENT GPUShaderStage = 1
)

// SDL_GPUVertexElementFormat - Specifies the format of a vertex attribute.
// (https://wiki.libsdl.org/SDL3/SDL_GPUVertexElementFormat)
type GPUVertexElementFormat uint32

const (
	GPU_VERTEXELEMENTFORMAT_INVALID      GPUVertexElementFormat = 0
	GPU_VERTEXELEMENTFORMAT_INT          GPUVertexElementFormat = 1
	GPU_VERTEXELEMENTFORMAT_INT2         GPUVertexElementFormat = 2
	GPU_VERTEXELEMENTFORMAT_INT3         GPUVertexElementFormat = 3
	GPU_VERTEXELEMENTFORMAT_INT4         GPUVertexElementFormat = 4
	GPU_VERTEXELEMENTFORMAT_UINT         GPUVertexElementFormat = 5
	GPU_VERTEXELEMENTFORMAT_UINT2        GPUVertexElementFormat = 6
	GPU_VERTEXELEMENTFORMAT_UINT3        GPUVertexElementFormat = 7
	GPU_VERTEXELEMENTFORMAT_UINT4        GPUVertexElementFormat = 8
	GPU_VERTEXELEMENTFORMAT_FLOAT        GPUVertexElementFormat = 9
	GPU_VERTEXELEMENTFORMAT_FLOAT2       GPUVertexElementFormat = 10
	GPU_VERTEXELEMENTFORMAT_FLOAT3       GPUVertexElementFormat = 11
	GPU_VERTEXELEMENTFORMAT_FLOAT4       GPUVertexElementFormat = 12
	GPU_VERTEXELEMENTFORMAT_BYTE2        GPUVertexElementFormat = 13
	GPU_VERTEXELEMENTFORMAT_BYTE4        GPUVertexElementFormat = 14
	GPU_VERTEXELEMENTFORMAT_UBYTE2       GPUVertexElementFormat = 15
	GPU_VERTEXELEMENTFORMAT_UBYTE4       GPUVertexElementFormat = 16
	GPU_VERTEXELEMENTFORMAT_BYTE2_NORM   GPUVertexElementFormat = 17
	GPU_VERTEXELEMENTFORMAT_BYTE4_NORM   GPUVertexElementFormat = 18
	GPU_VERTEXELEMENTFORMAT_UBYTE2_NORM  GPUVertexElementFormat = 19
	GPU_VERTEXELEMENTFORMAT_UBYTE4_NORM  GPUVertexElementFormat = 20
	GPU_VERTEXELEMENTFORMAT_SHORT2       GPUVertexElementFormat = 21
	GPU_VERTEXELEMENTFORMAT_SHORT4       GPUVertexElementFormat = 22
	GPU_VERTEXELEMENTFORMAT_USHORT2      GPUVertexElementFormat = 23
	GPU_VERTEXELEMENTFORMAT_USHORT4      GPUVertexElementFormat = 24
	GPU_VERTEXELEMENTFORMAT_SHORT2_NORM  GPUVertexElementFormat = 25
	GPU_VERTEXELEMENTFORMAT_SHORT4_NORM  GPUVertexElementFormat = 26
	GPU_VERTEXELEMENTFORMAT_USHORT2_NORM GPUVertexElementFormat = 27
	GPU_VERTEXELEMENTFORMAT_USHORT4_NORM GPUVertexElementFormat = 28
	GPU_VERTEXELEMENTFORMAT_HALF2        GPUVertexElementFormat = 29
	GPU_VERTEXELEMENTFORMAT_HALF4        GPUVertexElementFormat = 30
)

// SDL_GPUVertexInputRate - Specifies the rate at which vertex attributes are pulled from buffers.
// (https://wiki.libsdl.org/SDL3/SDL_GPUVertexInputRate)
type GPUVertexInputRate uint32

const (
	GPU_VERTEXINPUTRATE_VERTEX   GPUVertexInputRate = 0
	GPU_VERTEXINPUTRATE_INSTANCE GPUVertexInputRate = 1
)

// SDL_GPUFillMode - Specifies the fill mode of the graphics pipeline.
// (https://wiki.libsdl.org/SDL3/SDL_GPUFillMode)
type GPUFillMode uint32

const (
	GPU_FILLMODE_FILL GPUFillMode = 0
	GPU_FILLMODE_LINE GPUFillMode = 1
)

// SDL_GPUCullMode - Specifies the facing direction in which triangle faces will be culled.
// (https://wiki.libsdl.org/SDL3/SDL_GPUCullMode)
type GPUCullMode uint32

const (
	GPU_CULLMODE_NONE  GPUCullMode = 0
	GPU_CULLMODE_FRONT GPUCullMode = 1
	GPU_CULLMODE_BACK  GPUCullMode = 2
)

// SDL_GPUFrontFace - Specifies the vertex winding that will cause a triangle to be determined to be front-facing.
// (https://wiki.libsdl.org/SDL3/SDL_GPUFrontFace)
type GPUFrontFace uint32

const (
	GPU_FRONTFACE_COUNTER_CLOCKWISE GPUFrontFace = 0
	GPU_FRONTFACE_CLOCKWISE         GPUFrontFace = 1
)

// SDL_GPUCompareOp - Specifies a comparison operator for depth, stencil and sampler operations.
// (https://wiki.libsdl.org/SDL3/SDL_GPUCompareOp)
type GPUCompareOp uint32

const (
	GPU_COMPAREOP_INVALID          GPUCompareOp = 0
	GPU_COMPAREOP_NEVER            GPUCompareOp = 1
	GPU_COMPAREOP_LESS             GPUCompareOp = 2
	GPU_COMPAREOP_EQUAL            GPUCompareOp = 3
	GPU_COMPAREOP_LESS_OR_EQUAL    GPUCompareOp = 4
	GPU_COMPAREOP_GREATER          GPUCompareOp = 5
	GPU_COMPAREOP_NOT_EQUAL        GPUCompareOp = 6
	GPU_COMPAREOP_GREATER_OR_EQUAL GPUCompareOp = 7
	GPU_COMPAREOP_ALWAYS           GPUCompareOp = 8
)

// SDL_GPUStencilOp - Specifies what happens to a stored stencil value if stencil tests fail or pass.
// (https://wiki.libsdl.org/SDL3/SDL_GPUStencilOp)
type GPUStencilOp uint32

const (
	GPU_STENCILOP_INVALID             GPUStencilOp = 0
	GPU_STENCILOP_KEEP                GPUStencilOp = 1
	GPU_STENCILOP_ZERO                GPUStencilOp = 2
	GPU_STENCILOP_REPLACE             GPUStencilOp = 3
	GPU_STENCILOP_INCREMENT_AND_CLAMP GPUStencilOp = 4
	GPU_STENCILOP_DECREMENT_AND_CLAMP GPUStencilOp = 5
	GPU_STENCILOP_INVERT              GPUStencilOp = 6
	GPU_STENCILOP_INCREMENT_AND_WRAP  GPUStencilOp = 7
	GPU_STENCILOP_DECREMENT_AND_WRAP  GPUStencilOp = 8
)

// SDL_GPUBlendOp - Specifies the operator to be used when pixels in a render target are blended with existing pixels in the texture.
// (https://wiki.libsdl.org/SDL3/SDL_GPUBlendOp)
type GPUBlendOp uint32

const (
	GPU_BLENDOP_INVALID          GPUBlendOp = 0
	GPU_BLENDOP_ADD              GPUBlendOp = 1
	GPU_BLENDOP_SUBTRACT         GPUBlendOp = 2
	GPU_BLENDOP_REVERSE_SUBTRACT GPUBlendOp = 3
	GPU_BLENDOP_MIN              GPUBlendOp = 4
	GPU_BLENDOP_MAX              GPUBlendOp = 5
)

// SDL_GPUBlendFactor - Specifies a blending factor to be used when pixels in a render target are blended with existing pixels in the texture.
// (https://wiki.libsdl.org/SDL3/SDL_GPUBlendFactor)
type GPUBlendFactor uint32

const (
	GPU_BLENDFACTOR_INVALID                  GPUBlendFactor = 0
	GPU_BLENDFACTOR_ZERO                     GPUBlendFactor = 1
	GPU_BLENDFACTOR_ONE                      GPUBlendFactor = 2
	GPU_BLENDFACTOR_SRC_COLOR                GPUBlendFactor = 3
	GPU_BLENDFACTOR_ONE_MINUS_SRC_COLOR      GPUBlendFactor = 4
	GPU_BLENDFACTOR_DST_COLOR                GPUBlendFactor = 5
	GPU_BLENDFACTOR_ONE_MINUS_DST_COLOR      GPUBlendFactor = 6
	GPU_BLENDFACTOR_SRC_ALPHA                GPUBlendFactor = 7
	GPU_BLENDFACTOR_ONE_MINUS_SRC_ALPHA      GPUBlendFactor = 8
	GPU_BLENDFACTOR_DST_ALPHA                GPUBlendFactor = 9
	GPU_BLENDFACTOR_ONE_MINUS_DST_ALPHA      GPUBlendFactor = 10
	GPU_BLENDFACTOR_CONSTANT_COLOR           GPUBlendFactor = 11
	GPU_BLENDFACTOR_ONE_MINUS_CONSTANT_COLOR GPUBlendFactor = 12
	GPU_BLENDFACTOR_SRC_ALPHA_SATURATE       GPUBlendFactor = 13
)

// SDL_GPUFilter - Specifies a filter operation used by a sampler.
// (https://wiki.libsdl.org/SDL3/SDL_GPUFilter)
type GPUFilter uint32

const (
	GPU_FILTER_NEAREST GPUFilter = 0
	GPU_FILTER_LINEAR  GPUFilter = 1
)

// SDL_GPUSamplerMipmapMode - Specifies a mipmap mode used by a sampler.
// (https://wiki.libsdl.org/SDL3/SDL_GPUSamplerMipmapMode)
type GPUSamplerMipmapMode uint32

const (
	GPU_SAMPLERMIPMAPMODE_NEAREST GPUSamplerMipmapMode = 0
	GPU_SAMPLERMIPMAPMODE_LINEAR  GPUSamplerMipmapMode = 1
)

// SDL_GPUSamplerAddressMode - Specifies behavior of texture sampling when the coordinates exceed the 0-1 range.
// (https://wiki.libsdl.org/SDL3/SDL_GPUSamplerAddressMode)
type GPUSamplerAddressMode uint32

const (
	GPU_SAMPLERADDRESSMODE_REPEAT          GPUSamplerAddressMode = 0
	GPU_SAMPLERADDRESSMODE_MIRRORED_REPEAT GPUSamplerAddressMode = 1
	GPU_SAMPLERADDRESSMODE_CLAMP_TO_EDGE   GPUSamplerAddressMode = 2
)

// SDL_GPUPresentMode - Specifies the timing that will be used to present swapchain textures to the OS.
// (https://wiki.libsdl.org/SDL3/SDL_GPUPresentMode)
type GPUPresentMode uint32

const (
	GPU_PRESENTMODE_VSYNC     GPUPresentMode = 0
	GPU_PRESENTMODE_IMMEDIATE GPUPresentMode = 1
	GPU_PRESENTMODE_MAILBOX   GPUPresentMode = 2
)

// SDL_GPUSwapchainComposition - Specifies the texture format and colorspace of the swapchain textures.
// (https://wiki.libsdl.org/SDL3/SDL_GPUSwapchainComposition)
type GPUSwapchainComposition uint32

const (
	GPU_SWAPCHAINCOMPOSITION_SDR                 GPUSwapchainComposition = 0
	GPU_SWAPCHAINCOMPOSITION_SDR_LINEAR          GPUSwapchainComposition = 1
	GPU_SWAPCHAINCOMPOSITION_HDR_EXTENDED_LINEAR GPUSwapchainComposition = 2
	GPU_SWAPCHAINCOMPOSITION_HDR10_ST2084        GPUSwapchainComposition = 3
)

// SDL_HintPriority - An enumeration of hint priorities.
// (https://wiki.libsdl.org/SDL3/SDL_HintPriority)
type HintPriority uint32

const (
	HINT_DEFAULT  HintPriority = 0
	HINT_NORMAL   HintPriority = 1
	HINT_OVERRIDE HintPriority = 2
)

// SDL_LogPriority - The predefined log priorities
// (https://wiki.libsdl.org/SDL3/SDL_LogPriority)
type LogPriority uint32

const (
	LOG_PRIORITY_INVALID  LogPriority = 0
	LOG_PRIORITY_TRACE    LogPriority = 1
	LOG_PRIORITY_VERBOSE  LogPriority = 2
	LOG_PRIORITY_DEBUG    LogPriority = 3
	LOG_PRIORITY_INFO     LogPriority = 4
	LOG_PRIORITY_WARN     LogPriority = 5
	LOG_PRIORITY_ERROR    LogPriority = 6
	LOG_PRIORITY_CRITICAL LogPriority = 7
	LOG_PRIORITY_COUNT    LogPriority = 8
)

// SDL_TextureAccess - The access pattern allowed for a texture.
// (https://wiki.libsdl.org/SDL3/SDL_TextureAccess)
type TextureAccess uint32

const (
	TEXTUREACCESS_STATIC    TextureAccess = 0
	TEXTUREACCESS_STREAMING TextureAccess = 1
	TEXTUREACCESS_TARGET    TextureAccess = 2
)

// SDL_RendererLogicalPresentation - How the logical size is mapped to the output.
// (https://wiki.libsdl.org/SDL3/SDL_RendererLogicalPresentation)
type RendererLogicalPresentation uint32

const (
	LOGICAL_PRESENTATION_DISABLED      RendererLogicalPresentation = 0
	LOGICAL_PRESENTATION_STRETCH       RendererLogicalPresentation = 1
	LOGICAL_PRESENTATION_LETTERBOX     RendererLogicalPresentation = 2
	LOGICAL_PRESENTATION_OVERSCAN      RendererLogicalPresentation = 3
	LOGICAL_PRESENTATION_INTEGER_SCALE RendererLogicalPresentation = 4
)

// SDL_Sandbox - Application sandbox environment.
// (https://wiki.libsdl.org/SDL3/SDL_Sandbox)
type Sandbox uint32

const (
	SANDBOX_NONE              Sandbox = 0
	SANDBOX_UNKNOWN_CONTAINER Sandbox = 1
	SANDBOX_FLATPAK           Sandbox = 2
	SANDBOX_SNAP              Sandbox = 3
	SANDBOX_MACOS             Sandbox = 4
)

// SDL_DateFormat - The preferred date format of the current system locale.
// (https://wiki.libsdl.org/SDL3/SDL_DateFormat)
type DateFormat uint32

const (
	DATE_FORMAT_YYYYMMDD DateFormat = 0
	DATE_FORMAT_DDMMYYYY DateFormat = 1
	DATE_FORMAT_MMDDYYYY DateFormat = 2
)

// SDL_TimeFormat - The preferred time format of the current system locale.
// (https://wiki.libsdl.org/SDL3/SDL_TimeFormat)
type TimeFormat uint32

const (
	TIME_FORMAT_24HR TimeFormat = 0
	TIME_FORMAT_12HR TimeFormat = 1
)
