package sdl

// Code generated by cmd/ffi2go. DO NOT EDIT.

type (
	SpinLock               int32
	PropertiesID           uint32
	ThreadID               uint64
	TLSID                  AtomicInt
	AudioDeviceID          uint32
	BlendMode              uint32
	SurfaceFlags           uint32
	CameraID               uint32
	DisplayID              uint32
	WindowID               uint32
	WindowFlags            uint64
	GLContext              *GLContextState
	EGLDisplay             uintptr
	EGLConfig              uintptr
	EGLSurface             uintptr
	SensorID               uint32
	JoystickID             uint32
	Keycode                uint32
	Keymod                 uint16
	KeyboardID             uint32
	MouseID                uint32
	MouseButtonFlags       uint32
	TouchID                uint64
	FingerID               uint64
	PenID                  uint32
	PenInputFlags          uint32
	GlobFlags              uint32
	GPUTextureUsageFlags   uint32
	GPUBufferUsageFlags    uint32
	GPUShaderFormat        uint32
	GPUColorComponentFlags uint8
	HapticID               uint32
	InitFlags              uint32
	MessageBoxFlags        uint32
	MessageBoxButtonFlags  uint32
	MetalView              uintptr
	TimerID                uint32
)
