package sdl

// Code generated by cmd/ffi2go. DO NOT EDIT.

type SpinLock int32

type PropertiesID uint32

type ThreadID uint64

type TLSID AtomicInt

type AudioDeviceID uint32

type BlendMode uint32

type SurfaceFlags uint32

type CameraID uint32

type DisplayID uint32

type WindowID uint32

type WindowFlags uint64

type GLContext *GLContextState

type EGLDisplay uintptr

type EGLConfig uintptr

type EGLSurface uintptr

type SensorID uint32

type JoystickID uint32

type Keycode uint32

type Keymod uint16

type KeyboardID uint32

type MouseID uint32

type MouseButtonFlags uint32

type TouchID uint64

type FingerID uint64

type PenID uint32

type PenInputFlags uint32

type GlobFlags uint32

type GPUTextureUsageFlags uint32

type GPUBufferUsageFlags uint32

type GPUShaderFormat uint32

type GPUColorComponentFlags uint8

type HapticEffectType uint16

type HapticDirectionType uint8

type HapticEffectID int32

type HapticID uint32

type InitFlags uint32

type MessageBoxFlags uint32

type MessageBoxButtonFlags uint32

type MetalView uintptr

type TimerID uint32

type TrayEntryFlags uint32
