//go:build windows || unix

package sdl

import (
	puregogen "github.com/Zyko0/purego-gen"
	purego "github.com/ebitengine/purego"
	"runtime"
	"unsafe"
)

// File generated by github.com/Zyko0/purego-gen. DO NOT EDIT.

var (
	// Symbols
	// sdl
	_addr_SDL_ShowMessageBox uintptr
)

func initialize_ex() {
	var err error

	// Symbols sdl
	_addr_SDL_ShowMessageBox, err = puregogen.OpenSymbol(_hnd_sdl, "SDL_ShowMessageBox")
	if err != nil {
		panic("cannot puregogen.OpenSymbol: SDL_ShowMessageBox")
	}

	iShowMessageBox = func(data *messageBoxData, buttonid *int32) bool {
		_r0, _, _ := purego.SyscallN(_addr_SDL_ShowMessageBox, uintptr(unsafe.Pointer(data)), uintptr(unsafe.Pointer(buttonid)))
		__r0 := _r0 != 0
		runtime.KeepAlive(data)
		runtime.KeepAlive(buttonid)
		return __r0
	}
}
