package ttf

// Code generated by cmd/ffi2go. DO NOT EDIT.

type HintingFlags uint32

const (
	HINTING_NORMAL         HintingFlags = 0
	HINTING_LIGHT          HintingFlags = 1
	HINTING_MONO           HintingFlags = 2
	HINTING_NONE           HintingFlags = 3
	HINTING_LIGHT_SUBPIXEL HintingFlags = 4
)

type HorizontalAlignment uint32

const (
	HORIZONTAL_ALIGN_INVALID HorizontalAlignment = 4294967295
	HORIZONTAL_ALIGN_LEFT    HorizontalAlignment = 0
	HORIZONTAL_ALIGN_CENTER  HorizontalAlignment = 1
	HORIZONTAL_ALIGN_RIGHT   HorizontalAlignment = 2
)

type Direction uint32

const (
	DIRECTION_INVALID Direction = 0
	DIRECTION_LTR     Direction = 4
	DIRECTION_RTL     Direction = 5
	DIRECTION_TTB     Direction = 6
	DIRECTION_BTT     Direction = 7
)

type ImageType uint32

const (
	IMAGE_INVALID ImageType = 0
	IMAGE_ALPHA   ImageType = 1
	IMAGE_COLOR   ImageType = 2
	IMAGE_SDF     ImageType = 3
)

type GPUTextEngineWinding uint32

const (
	GPU_TEXTENGINE_WINDING_INVALID           GPUTextEngineWinding = 4294967295
	GPU_TEXTENGINE_WINDING_CLOCKWISE         GPUTextEngineWinding = 0
	GPU_TEXTENGINE_WINDING_COUNTER_CLOCKWISE GPUTextEngineWinding = 1
)

type DrawCommand uint32

const (
	DRAW_COMMAND_NOOP DrawCommand = 0
	DRAW_COMMAND_FILL DrawCommand = 1
	DRAW_COMMAND_COPY DrawCommand = 2
)
