package ttf

import sdl "github.com/Zyko0/go-sdl3/sdl"

// Code generated by cmd/ffi2go. DO NOT EDIT.

type Font struct{}

type Text struct {
	Text     string
	NumLines int32
	Refcount int32
	Internal *TextData
}

type GPUAtlasDrawSequence struct {
	AtlasTexture *sdl.GPUTexture
	Xy           *sdl.FPoint
	Uv           *sdl.FPoint
	NumVertices  int32
	Indices      *int32
	NumIndices   int32
	ImageType    ImageType
	Next         *GPUAtlasDrawSequence
}

type SubString struct {
	Flags        SubStringFlags
	Offset       int32
	Length       int32
	LineIndex    int32
	ClusterIndex int32
	Rect         sdl.Rect
}

type FillOperation struct {
	Cmd  DrawCommand
	Rect sdl.Rect
}

type CopyOperation struct {
	Cmd        DrawCommand
	TextOffset int32
	GlyphFont  *Font
	GlyphIndex uint32
	Src        sdl.Rect
	Dst        sdl.Rect
	Reserved   Pointer
}

type TextLayout struct{}
