package mixer

// Code generated by cmd/ffi2go. DO NOT EDIT.

// MIX_Mixer - An opaque object that represents a mixer.
// (https://wiki.libsdl.org/SDL3_mixer/MIX_Mixer)
type Mixer struct{}

// MIX_Audio - An opaque object that represents audio data.
// (https://wiki.libsdl.org/SDL3_mixer/MIX_Audio)
type Audio struct{}

// MIX_Track - An opaque object that represents a source of sound output to be mixed.
// (https://wiki.libsdl.org/SDL3_mixer/MIX_Track)
type Track struct{}

// MIX_Group - An opaque object that represents a grouping of tracks.
// (https://wiki.libsdl.org/SDL3_mixer/MIX_Group)
type Group struct{}

// MIX_StereoGains - A set of per-channel gains for tracks using [MIX_SetTrackStereo](MIX_SetTrackStereo)().
// (https://wiki.libsdl.org/SDL3_mixer/MIX_StereoGains)
type StereoGains struct {
	Left  float32
	Right float32
}

// MIX_Point3D - 3D coordinates for [MIX_SetTrack3DPosition](MIX_SetTrack3DPosition).
// (https://wiki.libsdl.org/SDL3_mixer/MIX_Point3D)
type Point3D struct {
	X float32
	Y float32
	Z float32
}

// MIX_AudioDecoder - An opaque object that represents an audio decoder.
// (https://wiki.libsdl.org/SDL3_mixer/MIX_AudioDecoder)
type AudioDecoder struct{}
