package mixer

// Code generated by cmd/ffi2go. DO NOT EDIT.

// Mix_Fading - The different fading types supported
// (https://wiki.libsdl.org/SDL3_mixer/Mix_Fading)
type Fading uint32

const (
	MIX_NO_FADING  Fading = 0
	MIX_FADING_OUT Fading = 1
	MIX_FADING_IN  Fading = 2
)

// Mix_MusicType - These are types of music files (not libraries used to load them)
// (https://wiki.libsdl.org/SDL3_mixer/Mix_MusicType)
type MusicType uint32

const (
	MUS_NONE           MusicType = 0
	MUS_WAV            MusicType = 1
	MUS_MOD            MusicType = 2
	MUS_MID            MusicType = 3
	MUS_OGG            MusicType = 4
	MUS_MP3            MusicType = 5
	MUS_MP3_MAD_UNUSED MusicType = 6
	MUS_FLAC           MusicType = 7
	MUS_MODPLUG_UNUSED MusicType = 8
	MUS_OPUS           MusicType = 9
	MUS_WAVPACK        MusicType = 10
	MUS_GME            MusicType = 11
)
