package mixer

// Code generated by cmd/ffi2go. DO NOT EDIT.

type Mixer struct{}

type Audio struct{}

type Track struct{}

type Group struct{}

type StereoGains struct {
	Left  float32
	Right float32
}

type Point3D struct {
	X float32
	Y float32
	Z float32
}

type AudioDecoder struct{}
