package mixer

// Code generated by cmd/ffi2go. DO NOT EDIT.

// Mix_Music - The internal format for a music chunk interpreted via codecs
// (https://wiki.libsdl.org/SDL3_mixer/Mix_Music)
type Music struct{}
