package img

import sdl "github.com/Zyko0/go-sdl3"

// Code generated by cmd/ffi2go. DO NOT EDIT.

type Animation struct {
	W      int32
	H      int32
	Count  int32
	Frames **sdl.Surface
	Delays *int32
}
